package pbscommon

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"errors"
	"strings"
	"testing"
)

// Golden vectors generated by testdata/gen_crypt_vectors.py through OpenSSL's
// libcrypto (the library proxmox-backup-client uses), so these tests check the
// Go implementation against OpenSSL, not against itself. The fingerprint also
// matches the one hard-coded in proxmox-backup's own key-config tests.
const (
	vecKey         = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
	vecIDKey       = "7c2c013efd07f3b25717a485263343cd4d292a4b65c200bb3b18ea227abe225c"
	vecFingerprint = "0e:ab:d4:46:0b:6e:b9:ca:34:50:23:de:e2:b7:78:c7:90:e5:4a:16:83:b9:65:9c:0a:57:ae:19:90:90:15:9b"
	vecDigestInput = "Proxmox Backup chunk digest test vector"
	vecDigest      = "2c292dda7d7c3cd5561b8f4a56635dddbb82d6878359111fa290eadbc511f3ee"
	vecBlobPlain   = "Proxmox Backup encrypted blob test vector. Proxmox Backup encrypted blob test vector. Proxmox Backup encrypted blob test vector. "
	vecBlobIV      = "6465666768696a6b6c6d6e6f70717273"
	vecBlob        = "7b6785be222d4cf09df16b906465666768696a6b6c6d6e6f707172737d730ffd7711ddaab040c73e878b67d388c12c29897b5ff8f098cee232a7cc0034122ab9ec9b856fe5e27801fbd773ad08b5aeba05a897ae73216f55651eb45fb62564b5c0822f965034bb71d33dfa5c017cc3ae1b88b320ac1c1cbd4541df191f6143805d6747941e26cbc9d545200af018ee53faae1d36cc0d9afe87dfc3d16767757b1a2425a82777d5a261e9c98c53"
	vecPassphrase  = "correct horse battery"
	vecManifestSig = "476a3753996087955a6716d717270b9b1b880599b3fed97725077448c540b72c"
)

const vecKeyfileScrypt = `{"kdf": {"Scrypt": {"n": 65536, "r": 8, "p": 1, "salt": "yMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5uc="}}, "created": "2026-09-30T12:00:00+02:00", "modified": "2026-09-30T12:00:00+02:00", "data": "MjM0NTY3ODk6Ozw9Pj9AQS9y+1ZDO3RKqC2a/i42IUQHHuvDc5i/5/oKFXwec3pch1cc2ZSAFjm2ruQbH6ZdWg==", "fingerprint": "0e:ab:d4:46:0b:6e:b9:ca:34:50:23:de:e2:b7:78:c7:90:e5:4a:16:83:b9:65:9c:0a:57:ae:19:90:90:15:9b", "hint": "test"}`

const vecKeyfilePBKDF2 = `{"kdf": {"PBKDF2": {"iter": 65535, "salt": "yMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5uc="}}, "created": "2026-09-30T12:00:00+02:00", "modified": "2026-09-30T12:00:00+02:00", "data": "MjM0NTY3ODk6Ozw9Pj9AQUpTHaIooV7g8/Qag+aehlaVhhyS6jn4w+vVa1sQLi1P+eDOpEttZRQ7YZCwhPqbZQ==", "fingerprint": "0e:ab:d4:46:0b:6e:b9:ca:34:50:23:de:e2:b7:78:c7:90:e5:4a:16:83:b9:65:9c:0a:57:ae:19:90:90:15:9b", "hint": "test"}`

const vecManifestCanonical = "{\"backup-id\":\"win-dc01\",\"backup-time\":1790000000,\"backup-type\":\"host\",\"files\":[{\"crypt-mode\":\"encrypt\",\"csum\":\"abababababababababababababababababababababababababababababababab\",\"filename\":\"C.pxar.didx\",\"size\":123456789012},{\"crypt-mode\":\"encrypt\",\"csum\":\"cdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd\",\"filename\":\"catalog.pcat1.didx\",\"size\":42}]}"

// vecCanonicalInput / vecCanonical check string escaping: serde_json (unlike
// encoding/json) leaves <, >, &, / and U+2028 raw and uses \b \f short forms.
const vecCanonicalInput = "R&D <files> \u00e9t\u00e9 \u2028 tab\there \u0001\u001f \"q\" \\ / \b\f\r\n"

const vecCanonical = "{\"a\":[true,false,1],\"s\":\"R&D <files> \u00e9t\u00e9 \u2028 tab\\there \\u0001\\u001f \\\"q\\\" \\\\ / \\b\\f\\r\\n\"}"

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func vecCrypt(t *testing.T) *CryptConfig {
	t.Helper()
	var key [KeySize]byte
	copy(key[:], mustHex(t, vecKey))
	cc, err := NewCryptConfig(key)
	if err != nil {
		t.Fatal(err)
	}
	return cc
}

func TestCryptConfigVectors(t *testing.T) {
	cc := vecCrypt(t)
	if got := hex.EncodeToString(cc.idKey[:]); got != vecIDKey {
		t.Errorf("id_key = %s, want %s", got, vecIDKey)
	}
	if got := cc.FingerprintString(); got != vecFingerprint {
		t.Errorf("fingerprint = %s, want %s", got, vecFingerprint)
	}
	if got := cc.ShortFingerprint(); got != vecFingerprint[:23] {
		t.Errorf("short fingerprint = %s, want %s", got, vecFingerprint[:23])
	}
	d := cc.ChunkDigest([]byte(vecDigestInput))
	if got := hex.EncodeToString(d[:]); got != vecDigest {
		t.Errorf("digest = %s, want %s", got, vecDigest)
	}
}

func TestChunkDigestNilIsPlainSHA256(t *testing.T) {
	var cc *CryptConfig
	d := cc.ChunkDigest([]byte("abc"))
	if got := hex.EncodeToString(d[:]); got != "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" {
		t.Errorf("nil ChunkDigest = %s", got)
	}
}

func TestEncryptedBlobMatchesOpenSSL(t *testing.T) {
	cc := vecCrypt(t)
	var iv [blobIVSize]byte
	copy(iv[:], mustHex(t, vecBlobIV))
	got := encryptBlob([]byte(vecBlobPlain), false, cc, iv)
	if hex.EncodeToString(got) != vecBlob {
		t.Fatalf("encrypted blob mismatch\n got %x\nwant %s", got, vecBlob)
	}
	plain, err := DecodeBlob(mustHex(t, vecBlob), cc)
	if err != nil {
		t.Fatal(err)
	}
	if string(plain) != vecBlobPlain {
		t.Fatalf("decoded %q", plain)
	}
}

func TestBlobRoundTrip(t *testing.T) {
	cc := vecCrypt(t)
	compressible := bytes.Repeat([]byte("nimbus backup "), 4096)
	random := make([]byte, 4096)
	for i := range random {
		random[i] = byte(i*7919 + i>>3)
	}
	for _, tc := range []struct {
		name     string
		data     []byte
		crypt    *CryptConfig
		compress bool
		magic    []byte
	}{
		{"plain", random, nil, false, blobUncompressedMagic},
		{"plain-compressed", compressible, nil, true, blobCompressedMagic},
		{"encrypted", random, cc, false, blobEncryptedMagic},
		{"encrypted-compressed", compressible, cc, true, blobEncrComprMagic},
		{"empty-encrypted", []byte{}, cc, true, blobEncryptedMagic},
	} {
		t.Run(tc.name, func(t *testing.T) {
			raw, err := EncodeBlob(tc.data, tc.crypt, tc.compress, CompressionFastest)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(raw[:8], tc.magic) {
				t.Fatalf("magic %v, want %v", raw[:8], tc.magic)
			}
			if IsEncryptedBlob(raw) != (tc.crypt != nil) {
				t.Fatalf("IsEncryptedBlob = %v", IsEncryptedBlob(raw))
			}
			got, err := DecodeBlob(raw, tc.crypt)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(got, tc.data) {
				t.Fatal("round trip mismatch")
			}
		})
	}
}

func TestDecodeEncryptedBlobFailures(t *testing.T) {
	cc := vecCrypt(t)
	raw := mustHex(t, vecBlob)
	if _, err := DecodeBlob(raw, nil); !errors.Is(err, ErrEncryptedNoKey) {
		t.Errorf("no key: err = %v, want ErrEncryptedNoKey", err)
	}
	other, err := NewCryptConfig([KeySize]byte{1})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := DecodeBlob(raw, other); err == nil {
		t.Error("wrong key accepted")
	}
	tampered := append([]byte(nil), raw...)
	tampered[len(tampered)-1] ^= 1
	if _, err := DecodeBlob(tampered, cc); err == nil {
		t.Error("tampered ciphertext accepted")
	}
	if _, err := DecodeBlob(raw[:30], cc); err == nil {
		t.Error("truncated blob accepted")
	}
}

func TestKeyFileVectors(t *testing.T) {
	want := mustHex(t, vecKey)
	for name, file := range map[string]string{"scrypt": vecKeyfileScrypt, "pbkdf2": vecKeyfilePBKDF2} {
		t.Run(name, func(t *testing.T) {
			kc, err := ParseKeyConfig([]byte(file))
			if err != nil {
				t.Fatal(err)
			}
			if !kc.NeedsPassphrase() {
				t.Fatal("NeedsPassphrase = false")
			}
			if _, err := kc.Decrypt(nil); !errors.Is(err, ErrKeyNeedsPassphrase) {
				t.Fatalf("no passphrase: err = %v", err)
			}
			if _, err := kc.Decrypt([]byte("wrong passphrase")); err == nil || !strings.Contains(err.Error(), "hint: test") {
				t.Fatalf("wrong passphrase: err = %v", err)
			}
			key, err := kc.Decrypt([]byte(vecPassphrase))
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(key[:], want) {
				t.Fatalf("key = %x", key)
			}
		})
	}
}

func TestKeyFileRoundTrip(t *testing.T) {
	key, err := GenerateKey()
	if err != nil {
		t.Fatal(err)
	}
	for _, pass := range []string{"", "a long passphrase"} {
		kc, err := NewKeyConfig(key, []byte(pass), "")
		if err != nil {
			t.Fatal(err)
		}
		raw, err := kc.Marshal()
		if err != nil {
			t.Fatal(err)
		}
		// Shape PBS expects: kdf is null or {"Scrypt":{...}}, fingerprint set.
		var generic map[string]any
		if err := json.Unmarshal(raw, &generic); err != nil {
			t.Fatal(err)
		}
		if pass == "" && generic["kdf"] != nil {
			t.Errorf("kdf = %v, want null", generic["kdf"])
		}
		if pass != "" {
			if _, ok := generic["kdf"].(map[string]any)["Scrypt"]; !ok {
				t.Errorf("kdf = %v, want Scrypt", generic["kdf"])
			}
		}
		if len(kc.Created) != 20 && len(kc.Created) != 25 {
			t.Errorf("created %q is not PBS RFC 3339", kc.Created)
		}
		back, err := ParseKeyConfig(raw)
		if err != nil {
			t.Fatal(err)
		}
		got, err := back.Decrypt([]byte(pass))
		if err != nil {
			t.Fatal(err)
		}
		if got != key {
			t.Fatal("round trip key mismatch")
		}
	}
	if _, err := NewKeyConfig(key, []byte("abc"), ""); err == nil {
		t.Error("short passphrase accepted")
	}
}

func TestKeyFileWrongFingerprint(t *testing.T) {
	kc, err := NewKeyConfig([KeySize]byte{1, 2, 3}, nil, "")
	if err != nil {
		t.Fatal(err)
	}
	kc.Fingerprint = vecFingerprint
	if _, err := kc.Decrypt(nil); err == nil {
		t.Error("mismatching fingerprint accepted")
	}
}

func vecManifest() BackupManifest {
	return BackupManifest{
		BackupID:   "win-dc01",
		BackupTime: 1790000000,
		BackupType: "host",
		// Not part of the PBS schema: PBS drops it when it rewrites the
		// manifest, so it must not be signed.
		Comment: "ignored by the signature",
		Files: []File{
			{CryptMode: "encrypt", Csum: strings.Repeat("ab", 32), Filename: "C.pxar.didx", Size: 123456789012},
			{CryptMode: "encrypt", Csum: strings.Repeat("cd", 32), Filename: "catalog.pcat1.didx", Size: 42},
		},
		Unprotected: Unprotected{ChunkUploadStats: ChunkUploadStats{Count: 3}},
	}
}

func TestCanonicalJSON(t *testing.T) {
	var buf bytes.Buffer
	err := writeCanonicalJSON(&buf, map[string]any{
		"s": vecCanonicalInput,
		"a": []any{true, false, json.Number("1")},
	})
	if err != nil {
		t.Fatal(err)
	}
	if buf.String() != vecCanonical {
		t.Fatalf("canonical json\n got %s\nwant %s", buf.String(), vecCanonical)
	}
}

func TestManifestCanonicalAndSignature(t *testing.T) {
	cc := vecCrypt(t)
	raw, err := json.Marshal(toSignedManifest(vecManifest()))
	if err != nil {
		t.Fatal(err)
	}
	obj, err := decodeJSONObject(raw)
	if err != nil {
		t.Fatal(err)
	}
	delete(obj, "unprotected")
	delete(obj, "signature")
	var buf bytes.Buffer
	if err := writeCanonicalJSON(&buf, obj); err != nil {
		t.Fatal(err)
	}
	if buf.String() != vecManifestCanonical {
		t.Fatalf("canonical json\n got %s\nwant %s", buf.String(), vecManifestCanonical)
	}
	sig, err := ManifestSignature(vecManifest(), cc)
	if err != nil {
		t.Fatal(err)
	}
	if got := hex.EncodeToString(sig[:]); got != vecManifestSig {
		t.Fatalf("signature = %s, want %s", got, vecManifestSig)
	}
}

// pbsRewrite mimics what PBS does to index.json.blob when the backup finishes
// (update_manifest): parse into its typed manifest (dropping unknown members),
// update "unprotected", and re-serialize pretty-printed.
func pbsRewrite(t *testing.T, raw []byte) []byte {
	t.Helper()
	var obj map[string]any
	if err := json.Unmarshal(raw, &obj); err != nil {
		t.Fatal(err)
	}
	kept := map[string]any{}
	for _, k := range []string{"backup-type", "backup-id", "backup-time", "files", "unprotected", "signature"} {
		if v, ok := obj[k]; ok {
			kept[k] = v
		}
	}
	kept["unprotected"].(map[string]any)["chunk_upload_stats"] = map[string]any{"count": 99, "size": 1234}
	kept["unprotected"].(map[string]any)["verify_state"] = map[string]any{"state": "ok"}
	out, err := json.MarshalIndent(kept, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func TestEncodeVerifyManifest(t *testing.T) {
	cc := vecCrypt(t)
	raw, err := EncodeManifest(vecManifest(), cc)
	if err != nil {
		t.Fatal(err)
	}
	var m BackupManifest
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatal(err)
	}
	if m.Signature != vecManifestSig || m.Unprotected.KeyFingerprint != vecFingerprint {
		t.Fatalf("signature %v fingerprint %q", m.Signature, m.Unprotected.KeyFingerprint)
	}
	if m.Comment != "" {
		t.Errorf("encrypted manifest carries a comment: %q", m.Comment)
	}
	if err := VerifyManifest(raw, cc); err != nil {
		t.Fatalf("verify: %v", err)
	}
	if err := VerifyManifest(pbsRewrite(t, raw), cc); err != nil {
		t.Fatalf("verify after PBS rewrite: %v", err)
	}
	if err := VerifyManifest(raw, nil); !errors.Is(err, ErrEncryptedNoKey) {
		t.Errorf("verify without key: %v", err)
	}
	other, _ := NewCryptConfig([KeySize]byte{9})
	if err := VerifyManifest(raw, other); err == nil {
		t.Error("verify with wrong key succeeded")
	}
	tampered := bytes.Replace(raw, []byte("C.pxar.didx"), []byte("D.pxar.didx"), 1)
	if err := VerifyManifest(tampered, cc); err == nil {
		t.Error("tampered manifest verified")
	}
	// Dropping the (unsigned) fingerprint must not skip the signature check.
	stripped := bytes.Replace(tampered, []byte(`"key-fingerprint":"`+vecFingerprint+`"`), []byte(`"x":"y"`), 1)
	if bytes.Equal(stripped, tampered) {
		t.Fatal("test setup: fingerprint not found in manifest")
	}
	if err := VerifyManifest(stripped, cc); err == nil {
		t.Error("tampered manifest without fingerprint verified")
	}
	unsigned := bytes.Replace(raw, []byte(`"signature":"`+vecManifestSig+`"`), []byte(`"signature":null`), 1)
	if err := VerifyManifest(unsigned, cc); err == nil {
		t.Error("unsigned manifest with fingerprint verified")
	}

	plain, err := EncodeManifest(vecManifest(), nil)
	if err != nil {
		t.Fatal(err)
	}
	if err := VerifyManifest(plain, nil); err != nil {
		t.Errorf("unencrypted manifest: %v", err)
	}
	if err := VerifyManifest(plain, cc); err != nil {
		t.Errorf("unencrypted manifest with a key: %v", err)
	}
	if bytes.Contains(plain, []byte("key-fingerprint")) {
		t.Error("unencrypted manifest carries a key fingerprint")
	}
}

func TestDecodeBlobReportsMode(t *testing.T) {
	cc := vecCrypt(t)
	plainBlob, err := EncodeBlob([]byte("old unencrypted chunk"), nil, true, CompressionFastest)
	if err != nil {
		t.Fatal(err)
	}
	// A client holding a key must still read unencrypted chunks, and know they
	// are plain so it verifies them with plain SHA-256.
	data, encrypted, err := decodeBlob(plainBlob, cc)
	if err != nil || encrypted || string(data) != "old unencrypted chunk" {
		t.Fatalf("plain blob with key: %q %v %v", data, encrypted, err)
	}
	_, encrypted, err = decodeBlob(mustHex(t, vecBlob), cc)
	if err != nil || !encrypted {
		t.Fatalf("encrypted blob: %v %v", encrypted, err)
	}
}

func TestCanonicalRejectsNull(t *testing.T) {
	var buf bytes.Buffer
	if err := writeCanonicalJSON(&buf, map[string]any{"a": nil}); err == nil {
		t.Error("null accepted")
	}
}

func TestFingerprintParse(t *testing.T) {
	fp, err := ParseFingerprint(vecFingerprint)
	if err != nil {
		t.Fatal(err)
	}
	if FormatFingerprint(fp[:]) != vecFingerprint {
		t.Error("fingerprint round trip")
	}
	if _, err := ParseFingerprint("0e:ab"); err == nil {
		t.Error("short fingerprint accepted")
	}
}
