package pbscommon

import (
	"encoding/base64"
	"fmt"
	"strings"
	"testing"

	"rsc.io/qr"
)

// Golden key files generated by OpenSSL's libcrypto (the library
// proxmox-backup-client uses), protecting key 00 01 .. 1f with passphrase
// pkVecPassphrase. The fingerprint matches proxmox-backup's own tests.
const (
	pkVecPassphrase  = "correct horse battery"
	pkVecFingerprint = "0e:ab:d4:46:0b:6e:b9:ca:34:50:23:de:e2:b7:78:c7:90:e5:4a:16:83:b9:65:9c:0a:57:ae:19:90:90:15:9b"
	vecKeyfileScrypt = `{"kdf": {"Scrypt": {"n": 65536, "r": 8, "p": 1, "salt": "yMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5uc="}}, "created": "2026-09-30T12:00:00+02:00", "modified": "2026-09-30T12:00:00+02:00", "data": "MjM0NTY3ODk6Ozw9Pj9AQS9y+1ZDO3RKqC2a/i42IUQHHuvDc5i/5/oKFXwec3pch1cc2ZSAFjm2ruQbH6ZdWg==", "fingerprint": "0e:ab:d4:46:0b:6e:b9:ca:34:50:23:de:e2:b7:78:c7:90:e5:4a:16:83:b9:65:9c:0a:57:ae:19:90:90:15:9b", "hint": "test"}`
)

// testKeyConfig returns an unprotected key file for key {b, 0, 0, ...}.
func testKeyConfig(t *testing.T, b byte, hint string) *KeyConfig {
	t.Helper()
	key := make([]byte, BlobEncryptionKeySize)
	key[0] = b
	crypt, err := NewCryptConfig(key)
	if err != nil {
		t.Fatal(err)
	}
	return &KeyConfig{
		Created:     "2026-10-09T12:00:00Z",
		Modified:    "2026-10-09T12:00:00Z",
		Data:        base64.StdEncoding.EncodeToString(key),
		Fingerprint: crypt.Fingerprint(),
		Hint:        hint,
	}
}

// vecKeyfileScryptPretty is vecKeyfileScrypt as serde_json::to_string_pretty
// lays it out (generated with Python json.dumps(indent=2), same layout), i.e.
// what `proxmox-backup-client key paperkey` prints and puts in the QR code.
const vecKeyfileScryptPretty = `{
  "kdf": {
    "Scrypt": {
      "n": 65536,
      "r": 8,
      "p": 1,
      "salt": "yMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5uc="
    }
  },
  "created": "2026-09-30T12:00:00+02:00",
  "modified": "2026-09-30T12:00:00+02:00",
  "data": "MjM0NTY3ODk6Ozw9Pj9AQS9y+1ZDO3RKqC2a/i42IUQHHuvDc5i/5/oKFXwec3pch1cc2ZSAFjm2ruQbH6ZdWg==",
  "fingerprint": "0e:ab:d4:46:0b:6e:b9:ca:34:50:23:de:e2:b7:78:c7:90:e5:4a:16:83:b9:65:9c:0a:57:ae:19:90:90:15:9b",
  "hint": "test"
}`

func TestPaperKeyMatchesPBSLayout(t *testing.T) {
	kc, err := ParseKeyConfig([]byte(vecKeyfileScrypt))
	if err != nil {
		t.Fatal(err)
	}
	pk, err := NewPaperKey(kc)
	if err != nil {
		t.Fatal(err)
	}
	if pk.JSON != vecKeyfileScryptPretty {
		t.Errorf("paper key JSON =\n%s\nwant\n%s", pk.JSON, vecKeyfileScryptPretty)
	}
	wantText := paperKeyBegin + "\n" + vecKeyfileScryptPretty + "\n" + paperKeyEnd + "\n"
	if pk.Text != wantText {
		t.Errorf("paper key text =\n%s\nwant\n%s", pk.Text, wantText)
	}
}

func TestPaperKeyMarkerInHint(t *testing.T) {
	kc := testKeyConfig(t, 7, "x\n"+paperKeyEnd+"\n"+paperKeyBegin)
	pk, err := NewPaperKey(kc)
	if err != nil {
		t.Fatal(err)
	}
	got, err := ParseKeyConfig([]byte("Subject: s\n" + pk.Text))
	if err != nil {
		t.Fatal(err)
	}
	if got.Hint != kc.Hint {
		t.Errorf("hint = %q, want %q", got.Hint, kc.Hint)
	}
}

func TestPaperKeyNoHTMLEscaping(t *testing.T) {
	kc := testKeyConfig(t, 1, "<a&b>")
	pk, err := NewPaperKey(kc)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(pk.JSON, `"hint": "<a&b>"`) {
		t.Errorf("hint escaped, serde_json would not:\n%s", pk.JSON)
	}
}

// The text of a paper key, with or without what surrounds the markers, and
// the QR payload must all import back to the same key.
func TestPaperKeyImportsBack(t *testing.T) {
	kc, err := ParseKeyConfig([]byte(vecKeyfileScrypt))
	if err != nil {
		t.Fatal(err)
	}
	want, err := kc.CryptConfig([]byte(pkVecPassphrase))
	if err != nil {
		t.Fatal(err)
	}
	pk, err := NewPaperKey(kc)
	if err != nil {
		t.Fatal(err)
	}
	for name, in := range map[string]string{
		"qr payload": pk.JSON,
		"text":       pk.Text,
		"pbs text":   "Subject: my key\n\n" + pk.Text + "\n█▀▀▀▀▀█ qr art\n",
		"indented":   "  " + strings.ReplaceAll(pk.Text, "\n", "\r\n  "),
		"no end":     paperKeyBegin + "\n" + pk.JSON,
		"original":   vecKeyfileScrypt,
	} {
		got, err := ParseKeyConfig([]byte(in))
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		crypt, err := got.CryptConfig([]byte(pkVecPassphrase))
		if err != nil {
			t.Errorf("%s: %v", name, err)
			continue
		}
		if crypt.Fingerprint() != want.Fingerprint() || want.Fingerprint() != pkVecFingerprint {
			t.Errorf("%s: key mismatch", name)
		}
	}
}

// parseQRSVG rasterizes the "M x yhWv1h-Wz" runs qrSVG writes.
func parseQRSVG(t *testing.T, svg string, size, margin int) [][]bool {
	t.Helper()
	i := strings.Index(svg, ` d="`)
	j := strings.LastIndex(svg, `"/>`)
	if i < 0 || j < i {
		t.Fatalf("no path in SVG: %s", svg)
	}
	grid := make([][]bool, size)
	for y := range grid {
		grid[y] = make([]bool, size)
	}
	for _, run := range strings.Split(strings.TrimSuffix(svg[i+4:j], "z"), "z") {
		var x, y, w, w2 int
		if _, err := fmt.Sscanf(run, "M%d %dh%dv1h-%d", &x, &y, &w, &w2); err != nil || w != w2 {
			t.Fatalf("bad run %q: %v", run, err)
		}
		for k := 0; k < w; k++ {
			grid[y-margin][x-margin+k] = true
		}
	}
	return grid
}

func TestQRSVGMatchesCode(t *testing.T) {
	kc, err := ParseKeyConfig([]byte(vecKeyfileScrypt))
	if err != nil {
		t.Fatal(err)
	}
	pk, err := NewPaperKey(kc)
	if err != nil {
		t.Fatal(err)
	}
	code, err := qr.Encode(pk.JSON, qr.M)
	if err != nil {
		t.Fatal(err)
	}
	if (code.Size-17)%4 != 0 || code.Size < 21 {
		t.Fatalf("odd QR size %d", code.Size)
	}
	n := code.Size + 8
	if !strings.Contains(pk.QRSVG, fmt.Sprintf(`viewBox="0 0 %d %d"`, n, n)) {
		t.Errorf("viewBox does not include the 4-module quiet zone: %s", pk.QRSVG[:120])
	}
	grid := parseQRSVG(t, pk.QRSVG, code.Size, 4)
	for y := 0; y < code.Size; y++ {
		for x := 0; x < code.Size; x++ {
			if grid[y][x] != code.Black(x, y) {
				t.Fatalf("module (%d,%d) = %v, want %v", x, y, grid[y][x], code.Black(x, y))
			}
		}
	}
	// Top-left finder pattern: dark 7x7 ring, light ring, dark 3x3 core.
	for k := 0; k < 7; k++ {
		if !grid[0][k] || !grid[6][k] || !grid[k][0] || !grid[k][6] {
			t.Fatalf("finder pattern ring broken at %d", k)
		}
	}
	if grid[1][1] || !grid[3][3] {
		t.Fatal("finder pattern core broken")
	}
}

func TestPaperKeyHTMLEscapes(t *testing.T) {
	kc := testKeyConfig(t, 9, "</p><script>")
	pk, err := NewPaperKey(kc)
	if err != nil {
		t.Fatal(err)
	}
	page := string(pk.HTML(PaperKeyPage{
		Lang:    "fr",
		Title:   "Clé <b>",
		Subject: "Serveur & co",
		Notes:   []string{"<img src=x>"},
	}))
	for _, bad := range []string{"<script>", "<b>", "<img src=x>", "Serveur & co"} {
		if strings.Contains(page, bad) {
			t.Errorf("unescaped %q in page", bad)
		}
	}
	for _, good := range []string{`<html lang="fr">`, "Serveur &amp; co", paperKeyBegin, "<svg ", "&lt;script&gt;"} {
		if !strings.Contains(page, good) {
			t.Errorf("page lacks %q", good)
		}
	}
}

// An unprotected key prints "kdf": null first, as PBS serializes it.
func TestPaperKeyUnprotectedKDFIsNull(t *testing.T) {
	pk, err := NewPaperKey(testKeyConfig(t, 3, ""))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(pk.JSON, "{\n  \"kdf\": null,\n  \"created\": ") {
		t.Errorf("unexpected layout:\n%s", pk.JSON)
	}
}

func TestProtectKeyConfig(t *testing.T) {
	plain, err := testKeyConfig(t, 5, "").CryptConfig(nil)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := ProtectKeyConfig(plain, []byte("abc"), ""); err == nil {
		t.Error("short passphrase accepted")
	}
	kc, err := ProtectKeyConfig(plain, []byte("s3cret pass"), "the usual")
	if err != nil {
		t.Fatal(err)
	}
	if kc.KDF == nil || kc.KDF.KDF != "scrypt" || kc.KDF.N != 65536 || kc.KDF.R != 8 || kc.KDF.P != 1 {
		t.Fatalf("kdf = %+v", kc.KDF)
	}
	if _, err := kc.CryptConfig([]byte("wrong pass")); err == nil || !strings.Contains(err.Error(), "the usual") {
		t.Errorf("wrong passphrase: err = %v", err)
	}
	// Through the paper key text, as it would be typed back.
	pk, err := NewPaperKey(kc)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(pk.JSON, `"Scrypt": {`) {
		t.Errorf("protected paper key lacks the scrypt KDF:\n%s", pk.JSON)
	}
	back, err := ParseKeyConfig([]byte(pk.Text))
	if err != nil {
		t.Fatal(err)
	}
	got, err := back.CryptConfig([]byte("s3cret pass"))
	if err != nil {
		t.Fatal(err)
	}
	if got.Fingerprint() != plain.Fingerprint() {
		t.Errorf("fingerprint %s, want %s", got.Fingerprint(), plain.Fingerprint())
	}
}
